export const INITIALIZE_APP = 'INITIALIZE_APP';
export const INITIALIZE_SUCCESS = 'INITIALIZE_SUCCESS';
export const INITIALIZE_FAILURE = 'INITIALIZE_FAILURE';
export const INITIALISATION_STARTS = 'INITIALISATION_STARTS';

export const SET_ROADS_TO_DOWNLOAD = 'SET_ROADS_TO_DOWNLOAD';
export const SET_ROADS_DOWNLOADED = 'SET_ROADS_DOWNLOADED';
export const SET_SIGNS_TO_DOWNLOAD = 'SET_SIGNS_TO_DOWNLOAD';
export const SET_SIGNS_DOWNLOADED = 'SET_SIGNS_DOWNLOADED';
export const SET_BRIDGES_TO_DOWNLOAD = 'SET_BRIDGES_TO_DOWNLOAD';
export const SET_BRIDGES_DOWNLOADED = 'SET_BRIDGES_DOWNLOADED';
export const SET_DANGERS_TO_DOWNLOAD = 'SET_BRIDGES_TO_DOWNLOAD';
export const SET_DANGERS_DOWNLOADED = 'SET_BRIDGES_DOWNLOADED';

export const ITERATE_ROADS_DOWNLOADED = 'ITERATE_ROADS_DOWNLOADED';
export const ITERATE_SIGNS_DOWNLOADED = 'ITERATE_SIGNS_DOWNLOADED';
export const ITERATE_BRIDGES_DOWNLOADED = 'ITERATE_BRIDGES_DOWNLOADED';


export const ENABLE_ADD_MARKER_MODE = 'ENABLE_ADD_MARKER_MODE';
export const DISABLE_ADD_MARKER_MODE = 'DISABLE_ADD_MARKER_MODE';
export const SWITCH_ADD_MARKER_MODE = 'SWITCH_ADD_MARKER_MODE';
export const SWITCH_PULL_MARKER_MODE = 'SWITCH_PULL_MARKER_MODE';

export const SWITCH_SHOW_EDIT_MARKERS = 'SWITCH_SHOW_EDIT_MARKERS';
