export const SET_AWARE_SEGMENTS = 'SET_AWARE_SEGMENTS'
export const REQUEST_AWARE_SEGMENTS = 'REQUEST_AWARE_SEGMENTS'
export const REQUEST_AWARE_SEGMENTS_SUCCESS = 'REQUEST_AWARE_SEGMENTS_SUCCESS'
export const SET_ROUTE_PAPER = 'SET_ROUTE_PAPER'
