export const SET_CENTER = 'SET_CENTER';
export const SET_CENTER_AND_ZOOM = 'SET_CENTER_AND_ZOOM';
export const SET_ZOOM = 'SET_ZOOM';
export const GEOMETRY_WIGHT = 'GEOMETRY_WIGHT';
export const SET_VIEWPORT_COORDINATES = 'SET_VIEWPORT_COORDINATES';
