export const SELECT_ROAD = 'SELECT_ROAD';
export const SELECT_BRIDGE = 'SELECT_BRIDGE';
export const SELECT_DANGER_ROAD = 'SELECT_DANGER_ROAD';


export const SELECT_TUNNEL = 'SELECT_TUNNEL';
export const SELECT_PIPE = 'SELECT_PIPE';
export const SELECT_PIPELINE = 'SELECT_PIPELINE';


