export const START_USER_AUTH_FETCHING = 'START_USER_AUTH_FETCHING';
export const USER_AUTH_FETCHING_SUCCESS = 'USER_AUTH_FETCHING_SUCCESS';
export const USER_AUTH_FETCHING_FAILURE = 'USER_AUTH_FETCHING_FAILURE';
export const SET_USER_AUTH_PARAMS = 'SET_USER_AUTH_PARAMS';
