export const SET_WAYPOINT_TEMPLATE = 'SET_WAYPOINT_TEMPLATE';
export const SAVE_WAYPOINT_TEMPLATE = 'SAVE_WAYPOINT_TEMPLATE';
export const CHANGE_WAYPOINT_STATUS = 'CHANGE_WAYPOINT_STATUS';

export const CHANGE_WAYPOINT_COMMENT = 'CHANGE_WAYPOINT_COMMENT';
export const NEW_WAYPOINT_TEMPLATE = 'NEW_WAYPOINT_TEMPLATE';


export const CHANGE_CHECKPOINT_STATUS = 'CHANGE_CHECKPOINT_STATUS';
export const CHANGE_CHECKPOINT_POSITION = 'CHANGE_CHECKPOINT_POSITION';
export const ADD_CHECKPOINT_MARKER = 'ADD_CHECKPOINT_MARKER';
export const REMOVE_CHECKPOINT_MARKER = 'REMOVE_CHECKPOINT_MARKER';
export const CREATE_CHECKPOINT_MARKER = 'CREATE_CHECKPOINT_MARKER';
export const PUSH_CHECKPOINT_MARKER = 'CREATE_CHECKPOINT_MARKER';
export const PUSH_CHECKPOINT_MARKER_TO_START = 'PUSH_CHECKPOINT_MARKER_TO_START';
export const CHANGE_ALL_CHECKPOINTS = 'CHANGE_ALL_CHECKPOINTS';
export const SWAP_CHECKPOINTS_DIRECTION = 'SWAP_CHECKPOINTS_DIRECTION';
export const SAVE_DIRECTION = 'SAVE_DIRECTION';

export const CHANGE_NAME_OF_TEMPLATE_WAYPOINT = 'CHANGE_NAME_OF_TEMPLATE_WAYPOINT';
export const CHANGE_DISTRICT_OF_TEMPLATE_WAYPOINT = 'CHANGE_DISTRICT_OF_TEMPLATE_WAYPOINT';
export const CHANGE_IMPORTANCE_OF_TEMPLATE_WAYPOINT = 'CHANGE_IMPORTANCE_OF_TEMPLATE_WAYPOINT';


export const REMOVE_WAYPOINT = 'REMOVE_WAYPOINT';
export const QUIT_DIRECTION_WITHOUT_SAVING = 'QUIT_DIRECTION_WITHOUT_SAVING';

